// GENERATED by scripts/gen-historical-events.mjs from git history. Do not edit.
//
// Every event signature the Karwan escrow and vault contracts have EVER
// declared, across all revisions, unioned. Several appear in more than one
// shape because the shape changed between generations and both versions are on
// chain, emitted by contracts that are still deployed.
//
// One entry per topic0. Where a declaration only renamed its parameters
// (Slashed's jobId/seller became id/owner) the types are identical, so the
// topic is identical and only the NEWEST naming is kept. Anything reading these
// args by name must therefore accept the alternatives: see `first()` in
// lifetimeStats.ts.
//
// Used only by the all-time scan, to decode logs from retired contracts whose
// current ABI no longer describes them. Nothing that talks to a live contract
// should read this: use the real ABI for that.

import { parseAbi } from 'viem';

export const HISTORICAL_EVENT_SIGNATURES = [
  'event AgentApproved(address indexed owner, address indexed agent)',
  'event AgentBound(address indexed agent, address indexed owner)',
  'event AgentOwnerRegistered(address indexed agent, address indexed owner)',
  'event AgentUnbound(address indexed owner, address indexed agent)',
  'event ArbiterSet(address indexed arbiter)',
  'event AssignedPayout(bytes32 indexed jobId, address indexed assignee, uint256 amount)',
  'event AssignerSet(address indexed who, bool allowed)',
  'event AttestedWindowSet(uint64 secs)',
  'event CancelProposed(bytes32 indexed jobId, address indexed proposer, bool proposerIsBuyer, uint16 sellerBps)',
  'event CancelWithdrawn(bytes32 indexed jobId)',
  'event Claimed(uint256 indexed positionId, address indexed owner, uint256 principal)',
  'event ConsumerSet(address indexed consumer, bool authorized)',
  'event CoverageFloorSet(uint256 floor)',
  'event DeadlineExtended(bytes32 indexed jobId, uint64 newDeadline)',
  'event DeadlineHorizonSet(uint64 secs)',
  'event DeadlineReclaimed(bytes32 indexed jobId, uint256 amount, uint256 priorReleased, address indexed to)',
  'event DealTiming(bytes32 indexed jobId, uint64 deliveryDeadline, uint64 reviewWindow, uint64 reclaimGrace)',
  'event Delivered(bytes32 indexed jobId, uint8 milestoneIndex, bytes32 proofHash, uint64 claimDeadline)',
  'event DeliveryAttested(bytes32 indexed jobId, uint8 milestoneIndex, bool pass, bytes32 evidenceHash)',
  'event Deposited(uint256 indexed positionId, address indexed owner, uint256 principal)',
  'event DisputeLapsed(bytes32 indexed jobId, uint64 frozenSecs)',
  'event DisputeResolved(bytes32 indexed jobId, uint16 sellerBps, uint256 sellerCut, uint256 buyerCut, bytes32 rulingHash)',
  'event DisputeTimeoutSet(uint64 secs)',
  'event EscrowAccepted(bytes32 indexed jobId, address indexed seller, uint256 reservedAmount)',
  'event EscrowDisputed(bytes32 indexed jobId, string reasonHash)',
  'event EscrowFunded(bytes32 indexed jobId, address indexed buyer, address indexed seller, uint256 amount, uint8[] milestonePcts)',
  'event EscrowFunded(bytes32 indexed jobId, address indexed buyer, address indexed seller, uint256 dealAmount, uint256 fundedAmount, uint256 feeTotal, uint8[] milestonePcts, uint16 reservationBps)',
  'event EscrowFunded(bytes32 indexed jobId, address indexed buyer, address indexed seller, uint256 dealAmount, uint256 fundedAmount, uint256 feeTotal, uint8[] milestonePcts)',
  'event EscrowRefunded(bytes32 indexed jobId, uint256 amount, uint256 priorReleased)',
  'event EscrowRefunded(bytes32 indexed jobId, uint256 amount)',
  'event EscrowReleasedFromDispute(bytes32 indexed jobId, uint256 sellerTotal, uint256 feeTotal)',
  'event EscrowSet(address indexed escrow)',
  'event EscrowSettled(bytes32 indexed jobId, uint256 finalAmount)',
  'event EscrowSettled(bytes32 indexed jobId, uint256 sellerTotal, uint256 feeTotal)',
  'event ExtensionRequested(bytes32 indexed jobId, uint64 newDeadline)',
  'event FeeBpsSet(uint16 bps)',
  'event FeeCollected(bytes32 indexed jobId, uint8 milestoneIndex, uint256 amount, address indexed treasury)',
  'event IdleSwept(uint256 amount, uint256 atTreasuryAfter)',
  'event LiquidityPulled(uint256 amount, uint256 atTreasuryAfter)',
  'event MaxYieldBpsSet(uint16 bps)',
  'event MilestoneClaimed(bytes32 indexed jobId, uint8 milestoneIndex, uint256 amount, address indexed to)',
  'event MutualCancelled(bytes32 indexed jobId, uint16 sellerBps, uint256 sellerCut, uint256 buyerCut)',
  'event OperatorTransferred(address indexed previousOperator, address indexed newOperator)',
  'event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)',
  'event OwnershipTransferStarted(address indexed previousOwner, address indexed newOwner)',
  'event PayoutAssigned(bytes32 indexed jobId, address indexed assignee, uint128 amount)',
  'event PositionSlashedClosed(uint256 indexed positionId, address indexed owner)',
  'event ProgressReleased(bytes32 indexed jobId, uint8 milestoneIndex, uint256 amount, address indexed to)',
  'event Released(bytes32 indexed id, address indexed consumer, address indexed owner, uint256 amount)',
  'event Released(bytes32 indexed jobId, address indexed seller, uint256 amount)',
  'event ReputationRecordFailed(bytes32 indexed jobId, string reason)',
  'event Reserved(bytes32 indexed id, address indexed consumer, address indexed owner, uint256 amount, address beneficiary)',
  'event Reserved(bytes32 indexed jobId, address indexed seller, uint256 amount)',
  'event ReviewBoundsSet(uint64 minSecs, uint64 maxSecs)',
  'event ReviewWindowSet(uint64 secs)',
  'event Slashed(bytes32 indexed id, address indexed owner, address indexed beneficiary, uint256 amount)',
  'event SlashFailed(bytes32 indexed jobId, address indexed seller, string reason)',
  'event TellerSet(address indexed teller, address indexed usyc)',
  'event Unwrapped(uint256 shares, uint256 usdcAmount)',
  'event WithdrawalCancelled(uint256 indexed positionId, address indexed owner)',
  'event WithdrawalRequested(uint256 indexed positionId, address indexed owner, uint64 claimableAt)',
  'event Wrapped(uint256 usdcAmount, uint256 shares)',
  'event YieldBackstopSet(address indexed backstop)',
  'event YieldDeposited(address indexed operator, uint256 amount, uint256 outForYieldAfter, uint256 surplus)',
  'event YieldOperatorSet(address indexed operator)',
  'event YieldWiringLocked()',
  'event YieldWithdrawn(address indexed operator, uint256 amount, uint256 outForYieldAfter)',
] as const;

export const historicalEventsAbi = parseAbi(HISTORICAL_EVENT_SIGNATURES);
