// GENERATED by scripts/gen-deploy-ledger.mjs from contracts/broadcast. Do not edit.
// Regenerate after any deploy so the all-time numbers include the new contract.

export interface DeployedContract {
  name: 'KarwanEscrow' | 'KarwanVault';
  address: `0x${string}`;
  /// Block the CREATE landed in. The lifetime scan starts here rather than at
  /// genesis, which is what keeps the window count tractable.
  deployBlock: bigint;
}

/// Every KarwanEscrow and KarwanVault ever deployed to Arc Testnet, oldest
/// first. Retired generations stay in this list on purpose: they are exactly
/// what the all-time totals exist to include.
export const DEPLOY_LEDGER: readonly DeployedContract[] = [
  { name: 'KarwanEscrow', address: '0xe796bcdbdbfd01a8a01d640e0d3fecd21b127f95', deployBlock: 42001872n },
  { name: 'KarwanEscrow', address: '0x9ed65f925baf6b1d794a10cfddfae4e56cc4e5f8', deployBlock: 42126486n },
  { name: 'KarwanVault', address: '0x92b1223921944024f6615a604a2bda6ef1fee922', deployBlock: 42652721n },
  { name: 'KarwanEscrow', address: '0xb81d9093607e460e2e4fa971c75d9322e756b838', deployBlock: 42864777n },
  { name: 'KarwanVault', address: '0xb94dc420b88764aa6bc14978953129c0118690a0', deployBlock: 44224233n },
  { name: 'KarwanEscrow', address: '0xf5c7a294cdc7bfea4c0d1e9946b1aa07b3169f2b', deployBlock: 44224234n },
  { name: 'KarwanVault', address: '0xab26eb7c8462f26a03a9bf32a6e662faee64368e', deployBlock: 44227075n },
  { name: 'KarwanEscrow', address: '0x534dccfad1924fca46ea30dee5591fa3d96137b3', deployBlock: 44227075n },
  { name: 'KarwanVault', address: '0x3fe7bddea2b1d5255a0e865222dae00eeefc45da', deployBlock: 44498110n },
  { name: 'KarwanEscrow', address: '0xd0eb0e41f910a2f3a3d38c6d2024ac9b12714b1d', deployBlock: 44498110n },
  { name: 'KarwanVault', address: '0x2d4506284b2d778365b4b295100ef099f35973c5', deployBlock: 44647711n },
  { name: 'KarwanEscrow', address: '0x48797c04ee342067a68f29fbb19b577077d77301', deployBlock: 44647712n },
  { name: 'KarwanVault', address: '0x8a6e9a8e0bb561f8cdab1619ecc4585aaf126d73', deployBlock: 53596891n },
  { name: 'KarwanEscrow', address: '0x492844c46cef2d751433739fc3409b7a4a5ba9a7', deployBlock: 53596893n },
  { name: 'KarwanVault', address: '0xbeee1d1da5d010f0f2a67b183361a5cd90a40e2a', deployBlock: 53603794n },
  { name: 'KarwanEscrow', address: '0x9b7852eca5176f1717cc600657df6cd8c4425ad9', deployBlock: 53603801n },
  { name: 'KarwanVault', address: '0xa600bd772a032ec2b96a9a44545024e270418927', deployBlock: 53645426n },
  { name: 'KarwanEscrow', address: '0x0262a4dfec0e057caf80f124bfd2847581e82b63', deployBlock: 53645435n },
] as const;

export const ESCROW_DEPLOYMENTS = DEPLOY_LEDGER.filter((c) => c.name === 'KarwanEscrow');
export const VAULT_DEPLOYMENTS = DEPLOY_LEDGER.filter((c) => c.name === 'KarwanVault');
