// GENERATED by scripts/gen-deploy-ledger.mjs from contracts/broadcast. Do not edit.
// Regenerate after any deploy so the all-time numbers include the new contract.

export type ContractName = 'KarwanBusinessRegistry' | 'KarwanEscrow' | 'KarwanInvoiceRegistry' | 'KarwanJobBoard' | 'KarwanPOFinancing' | 'KarwanReputation' | 'KarwanTreasury' | 'KarwanVault' | 'KarwanYieldDistributor';

/// What the contract does, used to group the all-time breakdown. A page listing
/// fifty addresses with no grouping is a dump, not a report.
export type ContractKind = 'financing' | 'registry' | 'settlement' | 'staking' | 'treasury';

export interface DeployedContract {
  name: ContractName;
  kind: ContractKind;
  address: `0x${string}`;
  /// Block the CREATE landed in. The lifetime scan starts here rather than at
  /// genesis, which is what keeps the window count tractable.
  deployBlock: bigint;
}

/// Every Karwan contract ever deployed to Arc Testnet, oldest first. Retired
/// generations stay in this list on purpose: they are exactly what the all-time
/// totals exist to include.
export const DEPLOY_LEDGER: readonly DeployedContract[] = [
  { name: 'KarwanJobBoard', kind: 'registry', address: '0x6b32f87954483525b8fbbda27453f6454a745b2f', deployBlock: 42001872n },
  { name: 'KarwanEscrow', kind: 'settlement', address: '0xe796bcdbdbfd01a8a01d640e0d3fecd21b127f95', deployBlock: 42001872n },
  { name: 'KarwanReputation', kind: 'registry', address: '0xb2d80c6d34649873471d836847ca6498ecb072d2', deployBlock: 42001872n },
  { name: 'KarwanEscrow', kind: 'settlement', address: '0x9ed65f925baf6b1d794a10cfddfae4e56cc4e5f8', deployBlock: 42126486n },
  { name: 'KarwanVault', kind: 'staking', address: '0x92b1223921944024f6615a604a2bda6ef1fee922', deployBlock: 42652721n },
  { name: 'KarwanJobBoard', kind: 'registry', address: '0xb5c863322c174801610e6e19c25688232de27558', deployBlock: 42864775n },
  { name: 'KarwanEscrow', kind: 'settlement', address: '0xb81d9093607e460e2e4fa971c75d9322e756b838', deployBlock: 42864777n },
  { name: 'KarwanReputation', kind: 'registry', address: '0x622b2aa60a29be1f5f98a64fdc0fc4ba8c109723', deployBlock: 42864777n },
  { name: 'KarwanTreasury', kind: 'treasury', address: '0x07359769eaa10b2d7f74bf83f6dc5884c9cc8f64', deployBlock: 44045501n },
  { name: 'KarwanTreasury', kind: 'treasury', address: '0x8207e1849b4ce3e3779678920b8a0609ba4027f8', deployBlock: 44046942n },
  { name: 'KarwanJobBoard', kind: 'registry', address: '0x64c24d4c808a8b58435b76512c0bdd606086ea08', deployBlock: 44224233n },
  { name: 'KarwanVault', kind: 'staking', address: '0xb94dc420b88764aa6bc14978953129c0118690a0', deployBlock: 44224233n },
  { name: 'KarwanReputation', kind: 'registry', address: '0x9ede957e0b249e830fbd4bce8fdfd8c991c6eec7', deployBlock: 44224233n },
  { name: 'KarwanEscrow', kind: 'settlement', address: '0xf5c7a294cdc7bfea4c0d1e9946b1aa07b3169f2b', deployBlock: 44224234n },
  { name: 'KarwanJobBoard', kind: 'registry', address: '0x35224c2234263b5506a9f7bff4bb98e9fced3ff3', deployBlock: 44227074n },
  { name: 'KarwanVault', kind: 'staking', address: '0xab26eb7c8462f26a03a9bf32a6e662faee64368e', deployBlock: 44227075n },
  { name: 'KarwanReputation', kind: 'registry', address: '0xe06857af3a786191e06926c71fc4708f37227ddf', deployBlock: 44227075n },
  { name: 'KarwanEscrow', kind: 'settlement', address: '0x534dccfad1924fca46ea30dee5591fa3d96137b3', deployBlock: 44227075n },
  { name: 'KarwanVault', kind: 'staking', address: '0x3fe7bddea2b1d5255a0e865222dae00eeefc45da', deployBlock: 44498110n },
  { name: 'KarwanReputation', kind: 'registry', address: '0xf64e1684b6beeda7714011a09c7fc26f3b04b75f', deployBlock: 44498110n },
  { name: 'KarwanEscrow', kind: 'settlement', address: '0xd0eb0e41f910a2f3a3d38c6d2024ac9b12714b1d', deployBlock: 44498110n },
  { name: 'KarwanReputation', kind: 'registry', address: '0xbbac748ca8c7a47e39bd2aeadbaa4e9f96ae4442', deployBlock: 44647711n },
  { name: 'KarwanVault', kind: 'staking', address: '0x2d4506284b2d778365b4b295100ef099f35973c5', deployBlock: 44647711n },
  { name: 'KarwanTreasury', kind: 'treasury', address: '0xa5516f58ab4dbf1b4949723715d1310a8fbb6fba', deployBlock: 44647712n },
  { name: 'KarwanEscrow', kind: 'settlement', address: '0x48797c04ee342067a68f29fbb19b577077d77301', deployBlock: 44647712n },
  { name: 'KarwanTreasury', kind: 'treasury', address: '0xc761115fa5781bec09112510ba6151f3950add72', deployBlock: 45474431n },
  { name: 'KarwanYieldDistributor', kind: 'treasury', address: '0x9950b9a41a3e80930e451f2fedaeb81e80195d03', deployBlock: 45476130n },
  { name: 'KarwanTreasury', kind: 'treasury', address: '0x9d95e4810e7c8b815f1fb1ec02c19085f8c76573', deployBlock: 45542929n },
  { name: 'KarwanInvoiceRegistry', kind: 'financing', address: '0x20a7cdf59b5f304de2b22a75e49f52353273e4e4', deployBlock: 46307878n },
  { name: 'KarwanPOFinancing', kind: 'financing', address: '0xc91122eb88613c98d58616cd8973883142f74bb5', deployBlock: 46307878n },
  { name: 'KarwanBusinessRegistry', kind: 'registry', address: '0xc64d347c9fe451a3f1c8f4cf2d7a2e43d9aa771e', deployBlock: 46458020n },
  { name: 'KarwanReputation', kind: 'registry', address: '0x3ca5269b5c54d4c807ca0df7eeb2cb7a5327e77d', deployBlock: 53596890n },
  { name: 'KarwanVault', kind: 'staking', address: '0x8a6e9a8e0bb561f8cdab1619ecc4585aaf126d73', deployBlock: 53596891n },
  { name: 'KarwanTreasury', kind: 'treasury', address: '0xf09e7af8b380cd01bd0d009f83a6b668a47742ec', deployBlock: 53596892n },
  { name: 'KarwanEscrow', kind: 'settlement', address: '0x492844c46cef2d751433739fc3409b7a4a5ba9a7', deployBlock: 53596893n },
  { name: 'KarwanInvoiceRegistry', kind: 'financing', address: '0x50cf1849e32e6a17bbff6b1aa8b1f7b479ad6c12', deployBlock: 53596894n },
  { name: 'KarwanBusinessRegistry', kind: 'registry', address: '0xc1dc7a8379885676a6ea08e67b7defd9a235de71', deployBlock: 53596895n },
  { name: 'KarwanYieldDistributor', kind: 'treasury', address: '0xf0f5e9b00b92f3999021fd8b88ac75c351d93fc7', deployBlock: 53596896n },
  { name: 'KarwanReputation', kind: 'registry', address: '0xf793bf9b439b65389741019882e444c7fddfbddd', deployBlock: 53603789n },
  { name: 'KarwanVault', kind: 'staking', address: '0xbeee1d1da5d010f0f2a67b183361a5cd90a40e2a', deployBlock: 53603794n },
  { name: 'KarwanTreasury', kind: 'treasury', address: '0x50bee0f41a5b4d0dfc5777bed7cc355d98e8e1c2', deployBlock: 53603797n },
  { name: 'KarwanEscrow', kind: 'settlement', address: '0x9b7852eca5176f1717cc600657df6cd8c4425ad9', deployBlock: 53603801n },
  { name: 'KarwanInvoiceRegistry', kind: 'financing', address: '0xf026b263e4f08c0091efdd912cfad31101d22a11', deployBlock: 53603804n },
  { name: 'KarwanBusinessRegistry', kind: 'registry', address: '0x2da10a8727dee540bd10bd9e855bf8cbb32776ae', deployBlock: 53603808n },
  { name: 'KarwanYieldDistributor', kind: 'treasury', address: '0xc9955389ddfc26d6845a581838965e015e79c420', deployBlock: 53603813n },
  { name: 'KarwanPOFinancing', kind: 'financing', address: '0xe6550216f1752147c960b5de1e797918b27af406', deployBlock: 53609861n },
  { name: 'KarwanReputation', kind: 'registry', address: '0x8bd35853b986a04efded7f863aff34826fde69ee', deployBlock: 53645422n },
  { name: 'KarwanVault', kind: 'staking', address: '0xa600bd772a032ec2b96a9a44545024e270418927', deployBlock: 53645426n },
  { name: 'KarwanTreasury', kind: 'treasury', address: '0x5a642be344fc3a01999bf113197ddc1a163ee837', deployBlock: 53645431n },
  { name: 'KarwanEscrow', kind: 'settlement', address: '0x0262a4dfec0e057caf80f124bfd2847581e82b63', deployBlock: 53645435n },
  { name: 'KarwanInvoiceRegistry', kind: 'financing', address: '0xfb0debd5e2618881699ed9b02ce0c9b718a1c649', deployBlock: 53645438n },
  { name: 'KarwanBusinessRegistry', kind: 'registry', address: '0x77f4a1cc4c1f7bb35b23db679966b33b8d8b27cf', deployBlock: 53645443n },
  { name: 'KarwanYieldDistributor', kind: 'treasury', address: '0x9e4adfcfb46108ed7c2f3c1af1728aae937f336f', deployBlock: 53645446n },
  { name: 'KarwanPOFinancing', kind: 'financing', address: '0xf14b41bd1a07c9fe643aae8292422127d0221d6f', deployBlock: 53645806n },
  { name: 'KarwanPOFinancing', kind: 'financing', address: '0xe87ef70e19fa8bbfdc04b9310371a7006b86b60a', deployBlock: 53924246n },
] as const;

export const ESCROW_DEPLOYMENTS = DEPLOY_LEDGER.filter((c) => c.name === 'KarwanEscrow');
export const VAULT_DEPLOYMENTS = DEPLOY_LEDGER.filter((c) => c.name === 'KarwanVault');
