/// The operator market catalog: real offers and requests the Karwan team posts
/// from its own testnet accounts, fulfilled with test USDC. Each account takes
/// one group of five specialties by its position in the operator's request,
/// so no email or name lives in code.
///
/// Remote services name the client market they serve, across twelve regions.
/// Work that needs someone present stays in the Nigerian cities the team is in,
/// and goods ship from Lagos with honest delivery times.

export type Lane = 'service' | 'goods';

/// [title, description, base price in USDC, true when it needs someone on site]
export type OfferEntry = readonly [string, string, number, boolean?];
/// [brief, budget in USDC, true when it needs someone on site]
export type RequestEntry = readonly [string, number, boolean?];

export interface Specialty {
  id: string;
  lane: Lane;
  offers: readonly OfferEntry[];
  requests: readonly RequestEntry[];
}

export interface Market {
  /// How a title or sentence names the place, e.g. "the US".
  name: string;
  multiplier: number;
  detail: string;
}

/// Client markets for remote work.
export const SERVICE_MARKETS: readonly Market[] = [
  { name: 'Nigeria', multiplier: 1, detail: 'Delivered remotely, with calls in West Africa Time.' },
  { name: 'Kenya', multiplier: 1, detail: 'Delivered remotely, with calls in East Africa Time.' },
  { name: 'Ghana', multiplier: 1, detail: 'Delivered remotely, with calls in Ghana time.' },
  { name: 'Egypt', multiplier: 1, detail: 'Delivered remotely, with calls in Cairo time.' },
  { name: 'the UAE', multiplier: 1.2, detail: 'Delivered remotely, with calls in Gulf time.' },
  { name: 'India', multiplier: 1, detail: 'Delivered remotely, with calls in India time.' },
  { name: 'the Philippines', multiplier: 1, detail: 'Delivered remotely, with calls in Manila time.' },
  { name: 'Indonesia', multiplier: 1, detail: 'Delivered remotely, with calls in Jakarta time.' },
  { name: 'Brazil', multiplier: 1.05, detail: 'Delivered remotely, with calls in Sao Paulo time.' },
  { name: 'Mexico', multiplier: 1.05, detail: 'Delivered remotely, with calls in Mexico City time.' },
  { name: 'the UK', multiplier: 1.3, detail: 'Delivered remotely, with calls in UK hours.' },
  { name: 'the US', multiplier: 1.3, detail: 'Delivered remotely, with calls in US Eastern hours.' },
];

/// Where the team can turn up in person.
export const ONSITE_CITIES: readonly Market[] = [
  { name: 'Lagos', multiplier: 1, detail: 'On site anywhere in Lagos.' },
  { name: 'Abuja', multiplier: 1.1, detail: 'On site in Abuja, travel included.' },
  { name: 'Port Harcourt', multiplier: 1.15, detail: 'On site in Port Harcourt, travel included.' },
];

/// Goods ship from Lagos.
export const LOCAL_DELIVERY: Market = { name: 'Lagos', multiplier: 1, detail: 'Delivered within Lagos in 2 days.' };
export const SHIPPING_DESTINATIONS: readonly Market[] = [
  { name: 'Abuja', multiplier: 1.05, detail: 'Shipped from Lagos to Abuja in 3 days.' },
  { name: 'Accra', multiplier: 1.1, detail: 'Shipped from Lagos to Accra in 4 to 6 days.' },
  { name: 'Nairobi', multiplier: 1.15, detail: 'Shipped from Lagos to Nairobi in 5 to 7 days.' },
  { name: 'Johannesburg', multiplier: 1.15, detail: 'Shipped from Lagos to Johannesburg in 6 to 8 days.' },
  { name: 'Dubai', multiplier: 1.2, detail: 'Shipped from Lagos to Dubai in 6 to 9 days.' },
  { name: 'London', multiplier: 1.25, detail: 'Shipped from Lagos to London in 7 to 10 days.' },
  { name: 'Toronto', multiplier: 1.3, detail: 'Shipped from Lagos to Toronto in 8 to 12 days.' },
  { name: 'Houston', multiplier: 1.3, detail: 'Shipped from Lagos to Houston in 8 to 12 days.' },
];

export const SPECIALTIES: readonly Specialty[] = [
  {
    id: 'brand-design', lane: 'service',
    offers: [
      ['Logo design', 'An original logo with a mark and wordmark, supplied in SVG, PNG and PDF.', 120],
      ['Brand identity kit', 'Logo, colour palette, type pairing and a two-page usage guide.', 350],
      ['Business card design', 'Print-ready front and back design with bleed, in PDF.', 40],
      ['Social media profile kit', 'Profile image, cover banners and a post template sized for four platforms.', 60],
      ['Product packaging design', 'Print-ready packaging artwork for one product, fitted to your dieline.', 280],
      ['Flyer or poster design', 'A single-page flyer or poster in print and digital versions.', 45],
      ['Pitch deck design', 'Up to 15 slides designed from your content, in Keynote or PowerPoint.', 220],
      ['Brand refresh', 'An update of an existing logo and colours that keeps what customers recognise.', 300],
      ['Menu design', 'A restaurant or cafe menu in print and QR-friendly PDF formats.', 70],
      ['Letterhead and invoice template', 'Editable letterhead and invoice templates in Word and Google Docs.', 50],
    ],
    requests: [
      ['Need a clean logo and colour palette for a new food delivery brand.', 150],
      ['Looking for a designer to redo our pitch deck, about 12 slides.', 180],
      ['Need packaging artwork for a 250 ml juice bottle label.', 120],
      ['Want a set of business cards and a letterhead that match our logo.', 60],
      ['Need a flyer for a weekend pop-up market, print and Instagram sizes.', 40],
    ],
  },
  {
    id: 'social-content', lane: 'service',
    offers: [
      ['Instagram content pack', 'Twelve designed posts with captions, planned as a two-week grid.', 90],
      ['Short video edits for Reels or TikTok', 'Five vertical edits up to 30 seconds from your raw clips, with captions.', 110],
      ['Content calendar', 'A 30-day posting plan with themes, formats and suggested captions.', 60],
      ['LinkedIn ghostwriting', 'Eight LinkedIn posts in your voice, drafted from a short interview.', 150],
      ['Community management', 'Replies to comments and messages on two platforms, one hour each weekday for two weeks.', 200],
      ['Product launch campaign', 'A launch plan with teaser, launch and follow-up posts across three platforms.', 260],
      ['Carousel posts', 'Four educational carousels of up to eight slides each.', 55],
      ['Social media audit', 'A review of your profiles and last 30 posts with a prioritised fix list.', 70],
      ['X thread writing', 'Three threads of up to ten posts each on topics you choose.', 45],
      ['Creator outreach list', 'Twenty vetted creators in your niche with contact details and a pitch message.', 85],
    ],
    requests: [
      ['Need someone to plan and design a month of Instagram posts for a skincare brand.', 120],
      ['Looking for five short Reels edited from footage I already shot.', 90],
      ['Need a LinkedIn post series about our product launch, about eight posts.', 130],
      ['Want an audit of our TikTok and Instagram with clear next steps.', 60],
      ['Need a list of 20 micro-creators in fashion who take paid collaborations.', 70],
    ],
  },
  {
    id: 'copywriting', lane: 'service',
    offers: [
      ['Website copy', 'Copy for up to five pages: home, about, services, pricing and contact.', 180],
      ['Product descriptions', 'Ten product descriptions written for search and conversion.', 60],
      ['Email newsletter', 'One newsletter issue of about 600 words, ready to send.', 50],
      ['Blog article', 'A researched 1,200-word article with headings and a meta description.', 70],
      ['Sales page', 'Long-form sales page copy with headline options and FAQs.', 220],
      ['Email welcome sequence', 'Five automated welcome emails for new subscribers.', 140],
      ['About page and founder story', 'An about page that tells your story in under 500 words.', 65],
      ['Ad copy set', 'Ten ad variations for Meta or Google with headlines and descriptions.', 55],
      ['Proofreading and editing', 'A line edit and proofread of up to 3,000 words.', 35],
      ['App store listing copy', 'Title, subtitle and description for the App Store and Google Play.', 60],
    ],
    requests: [
      ['Need homepage and about page copy for a logistics startup.', 150],
      ['Looking for someone to write 20 product descriptions for an online store.', 100],
      ['Need a five-email welcome sequence for new newsletter subscribers.', 120],
      ['Want two blog articles a month on small business finance.', 110],
      ['Need our app store listing rewritten to improve installs.', 60],
    ],
  },
  {
    id: 'game-3d-art', lane: 'service',
    offers: [
      ['3D product render', 'Three photoreal renders of one product from your photos or CAD.', 150],
      ['Game character concept art', 'One character with front, side and back views.', 120],
      ['Low-poly game asset pack', 'Ten game-ready low-poly props with textures.', 180],
      ['2D sprite sheet', 'An animated sprite sheet with up to four actions.', 90],
      ['Isometric illustration', 'One detailed isometric scene for a site or pitch.', 110],
      ['3D logo animation', 'A five-second animated 3D version of your logo.', 100],
      ['Architectural visualisation', 'Two interior or exterior renders from your floor plans.', 250],
      ['Game UI kit', 'Menus, buttons and HUD elements in one consistent style.', 160],
      ['NFT or avatar collection base art', 'Base character art with twelve swappable traits.', 220],
      ['Texture and material pack', 'Twenty tileable PBR textures for one theme.', 80],
    ],
    requests: [
      ['Need three photoreal renders of a smart speaker for our store page.', 140],
      ['Looking for concept art of two characters for a mobile game.', 200],
      ['Need a game UI kit for a casual puzzle game.', 150],
      ['Want an animated 3D version of our logo for video intros.', 90],
      ['Need interior renders of a two-bedroom apartment from floor plans.', 220],
    ],
  },
  {
    id: 'event-planning', lane: 'service',
    offers: [
      ['Corporate event coordination', 'Planning and on-the-day coordination for an event up to 150 guests.', 400, true],
      ['Product launch event', 'Venue, run of show and supplier booking for a launch night.', 450, true],
      ['Birthday or private party planning', 'Theme, vendors and coordination for up to 80 guests.', 250, true],
      ['Conference logistics', 'Registration desk, badges and speaker handling for one day.', 350, true],
      ['Event supplier sourcing', 'Three quotes each for venue, catering and sound.', 90],
      ['Run of show and timeline', 'A minute-by-minute run of show for your event.', 60],
      ['Wedding day coordination', 'A coordinator on the day to keep the schedule and vendors on track.', 300, true],
      ['Virtual event production', 'Streaming setup, rehearsal and host support for a two-hour online event.', 200],
      ['Exhibition stand management', 'Setup, staffing plan and teardown for a trade fair stand.', 280, true],
      ['Event budget plan', 'A line-by-line budget with savings options.', 50],
    ],
    requests: [
      ['Need a coordinator for a 100-guest company dinner.', 350, true],
      ['Looking for someone to produce a two-hour online product launch.', 180],
      ['Need a run of show and supplier quotes for a community meetup.', 90],
      ['Want help staffing and managing our stand at a trade fair.', 250, true],
      ['Need a budget plan for a small conference.', 60],
    ],
  },
  {
    id: 'web-development', lane: 'service',
    offers: [
      ['Landing page build', 'A responsive one-page site built from your design or a clean template.', 250],
      ['Small business website', 'Up to five pages with a contact form, basic SEO and hosting setup.', 450],
      ['WordPress fixes', 'Fix up to three issues on an existing WordPress site.', 60],
      ['Online store setup', 'A Shopify or WooCommerce store with up to 20 products loaded.', 380],
      ['Website speed optimisation', 'Image, caching and script fixes with before and after scores.', 120],
      ['API integration', 'Connect your site or app to one third-party API, with tests.', 300],
      ['Bug fixing session', 'Two hours of debugging on a web app you already run.', 80],
      ['Contact form and email setup', 'A working contact form wired to your inbox with spam protection.', 45],
      ['Website migration', 'Move a site to a new host or domain with no lost pages.', 150],
      ['Custom admin dashboard', 'A simple admin dashboard over your existing data source.', 420],
    ],
    requests: [
      ['Need a landing page for a product waitlist, design is ready in Figma.', 200],
      ['Looking for a developer to fix checkout errors on our WooCommerce store.', 90],
      ['Need our website moved to a new host without downtime.', 120],
      ['Want a small internal dashboard that reads from a Google Sheet.', 180],
      ['Need a contact form and booking page added to an existing site.', 70],
    ],
  },
  {
    id: 'qa-testing', lane: 'service',
    offers: [
      ['Mobile app test pass', 'Manual test of core flows on Android and iOS, with a written bug report.', 140],
      ['Website cross-browser test', 'Checks on Chrome, Safari, Firefox and a phone, with screenshots of issues.', 90],
      ['Test case writing', 'Up to 40 test cases for a feature, in a spreadsheet you can reuse.', 110],
      ['Accessibility check', 'A WCAG 2.2 AA review of up to five pages with fixes listed.', 130],
      ['Automated UI tests', 'Playwright tests for up to five key user journeys.', 280],
      ['Payment flow testing', 'End-to-end checks of checkout and refunds in test mode.', 120],
      ['Usability review', 'A walkthrough of your sign-up and first task with clear findings.', 100],
      ['Release regression test', 'A full pass on your release checklist, with results within a day of the build.', 150],
      ['API testing', 'A Postman collection and checks for up to 20 endpoints.', 160],
      ['Localisation check', 'A review of text and layout in two languages for truncation and mistakes.', 90],
    ],
    requests: [
      ['Need a tester to go through our Android app before release and log bugs.', 110],
      ['Looking for an accessibility review of our sign-up and checkout pages.', 120],
      ['Need Playwright tests written for login, search and checkout.', 200],
      ['Want someone to test our payment flow end to end in sandbox mode.', 90],
      ['Need a usability review of our onboarding with five real tasks.', 80],
    ],
  },
  {
    id: 'technical-writing', lane: 'service',
    offers: [
      ['API documentation', 'Reference docs for up to 20 endpoints with request and response examples.', 260],
      ['Product user guide', 'A step-by-step guide for your product with screenshots.', 180],
      ['README and setup guide', 'A clear README with install, configuration and first-run steps.', 70],
      ['Help centre articles', 'Five help articles answering your most common support questions.', 120],
      ['Release notes', 'Customer-facing release notes written from your changelog.', 40],
      ['Developer onboarding emails', 'A four-email sequence that gets developers to their first API call.', 110],
      ['Standard operating procedures', 'Up to five internal SOPs written from interviews with your team.', 150],
      ['Whitepaper editing', 'A structural edit and proofread of a technical whitepaper up to 6,000 words.', 200],
      ['Tutorial with sample code', 'A working tutorial with runnable examples in one language.', 140],
      ['Product FAQ', 'Twenty clear questions and answers for your site.', 55],
    ],
    requests: [
      ['Need API reference docs for about 15 REST endpoints.', 200],
      ['Looking for someone to write help centre articles for our top support questions.', 100],
      ['Need SOPs written for our order fulfilment process.', 120],
      ['Want a getting-started tutorial for our SDK with code samples.', 130],
      ['Need our product FAQ rewritten in plain language.', 50],
    ],
  },
  {
    id: 'software-ai', lane: 'service',
    offers: [
      ['Customer support chatbot', 'A chatbot trained on your help docs, added to your site.', 350],
      ['WhatsApp order bot', 'A WhatsApp bot that takes orders and answers common questions.', 300],
      ['Workflow automation', 'One business workflow automated across your tools with Zapier, Make or code.', 150],
      ['AI document extraction', 'A script that pulls fields from invoices or forms into a spreadsheet.', 220],
      ['Internal AI assistant', 'A private assistant that answers questions from your company documents.', 400],
      ['Data scraping script', 'A scheduled script that collects public data you need into a sheet.', 130],
      ['Google Sheets automation', 'Formulas and Apps Script that remove a weekly manual task.', 80],
      ['AI content pipeline', 'A pipeline that drafts first versions of posts or descriptions for review.', 200],
      ['Telegram bot', 'A Telegram bot for alerts, sign-ups or simple payments.', 160],
      ['AI feature prototype', 'A working prototype of one AI feature inside your app.', 450],
    ],
    requests: [
      ['Need a WhatsApp bot that takes food orders and sends them to the kitchen.', 250],
      ['Looking for someone to automate invoice data entry from PDFs.', 180],
      ['Need a support chatbot trained on our help centre.', 300],
      ['Want our weekly sales report built automatically in Google Sheets.', 90],
      ['Need a Telegram bot that alerts our team about new orders.', 120],
    ],
  },
  {
    id: 'smart-contracts', lane: 'service',
    offers: [
      ['ERC-20 token contract', 'A standard token contract with tests and a deploy script.', 250],
      ['Escrow contract', 'A two-party escrow contract with release and refund, fully tested.', 450],
      ['Smart contract review', 'A line-by-line review of one contract up to 300 lines, with findings.', 400],
      ['NFT collection contract', 'An ERC-721 contract with mint, allowlist and royalties.', 300],
      ['Web3 wallet connection', 'Wallet connect and sign-in added to your web app.', 180],
      ['USDC payment button', 'A button that takes USDC payments on one chain, with receipts.', 200],
      ['Subgraph or indexer', 'An indexer for your contract events with a query API.', 280],
      ['Gas optimisation pass', 'Gas savings on one contract with before and after numbers.', 220],
      ['Contract deployment and verification', 'Deploy and verify your contracts on one network.', 90],
      ['Web3 dashboard', 'A read-only dashboard of balances and events for your contracts.', 350],
    ],
    requests: [
      ['Need a USDC checkout added to our online store.', 220],
      ['Looking for a review of a staking contract before launch.', 400],
      ['Need an escrow contract for freelance milestones, with tests.', 450],
      ['Want wallet sign-in added to our Next.js app.', 150],
      ['Need our contracts deployed and verified on a testnet.', 80],
    ],
  },
  {
    id: 'bookkeeping', lane: 'service',
    offers: [
      ['Monthly bookkeeping', 'Up to 150 transactions categorised and reconciled each month.', 120],
      ['Catch-up bookkeeping', 'Up to six months of books brought current.', 250],
      ['Invoicing and receipts setup', 'An invoicing workflow and receipt capture set up in your tool.', 60],
      ['Profit and loss statement', 'A monthly profit and loss statement with a short note on what changed.', 80],
      ['Payroll preparation', 'Payroll figures prepared for up to 10 staff.', 100],
      ['Expense tracking spreadsheet', 'A ready-to-use expense tracker with monthly summaries.', 45],
      ['Cash flow forecast', 'A 12-week cash flow forecast you can update weekly.', 150],
      ['Bank reconciliation', 'One account reconciled for one month, with gaps flagged.', 70],
      ['Year-end schedules', 'Year-end schedules prepared and ready for your accountant.', 300],
      ['Accounting software setup', 'QuickBooks, Xero or Wave set up with your chart of accounts.', 110],
    ],
    requests: [
      ['Need monthly bookkeeping for a small retail shop, about 100 transactions.', 100],
      ['Looking for help catching up on four months of unreconciled books.', 180],
      ['Need a 12-week cash flow forecast before a supplier negotiation.', 120],
      ['Want Xero set up for a new company with a simple chart of accounts.', 90],
      ['Need payroll prepared for eight staff this month.', 80],
    ],
  },
  {
    id: 'data-analysis', lane: 'service',
    offers: [
      ['Sales dashboard', 'A dashboard of revenue, orders and top products from your data.', 200],
      ['Spreadsheet cleanup', 'One messy Excel or Google Sheets file cleaned, deduplicated and structured.', 60],
      ['Customer survey analysis', 'Analysis of up to 500 responses with charts and key findings.', 140],
      ['Market research summary', 'A short report on size, competitors and pricing for one market.', 180],
      ['Website analytics review', 'What your traffic data says and what to change first.', 90],
      ['Data entry', 'Up to 500 records entered from documents into a spreadsheet.', 40],
      ['Financial model', 'A three-statement model with editable assumptions.', 260],
      ['SQL reporting queries', 'Up to five saved queries that answer your business questions.', 120],
      ['Pricing analysis', 'A review of your prices against competitors with recommendations.', 150],
      ['Monthly KPI report', 'A one-page KPI report with trends and notes.', 100],
    ],
    requests: [
      ['Need a sales dashboard built from our Shopify exports.', 160],
      ['Looking for someone to analyse 300 customer survey responses.', 110],
      ['Need a competitor pricing review for five phone accessory shops.', 100],
      ['Want a simple financial model for a seed fundraise.', 200],
      ['Need 400 supplier records entered and cleaned in a spreadsheet.', 50],
    ],
  },
  {
    id: 'virtual-assistance', lane: 'service',
    offers: [
      ['Inbox management', 'Daily inbox triage and replies for one week.', 80],
      ['Calendar and scheduling', 'Meeting scheduling and reminders for one week.', 60],
      ['Travel booking', 'Flights, hotel and an itinerary for one trip.', 45],
      ['Lead research', 'Fifty qualified leads with names, roles and emails.', 90],
      ['Customer support replies', 'Replies to support tickets for 10 hours over one week.', 100],
      ['Document formatting', 'Up to 30 pages formatted into a clean document.', 35],
      ['Online research task', 'Research on one question with sources, delivered as a summary.', 50],
      ['CRM data cleanup', 'Up to 1,000 CRM contacts cleaned and updated.', 85],
      ['Order processing', 'Online orders processed and tracked for one week.', 70],
      ['Supplier outreach', 'Up to 20 suppliers contacted and their quotes compared.', 75],
    ],
    requests: [
      ['Need a virtual assistant to manage my inbox for two weeks.', 120],
      ['Looking for 50 B2B leads in fintech with verified emails.', 80],
      ['Need help booking travel and meetings for a three-city sales trip.', 60],
      ['Want someone to contact 15 packaging suppliers and compare quotes.', 70],
      ['Need our CRM cleaned up, about 800 contacts.', 70],
    ],
  },
  {
    id: 'legal-docs', lane: 'service',
    offers: [
      ['Freelance contract template', 'A clear services contract you can reuse, drafted for your lawyer to review.', 80],
      ['Website terms and privacy policy', 'Terms of use and a privacy policy drafted from your product, for legal review.', 120],
      ['Non-disclosure agreement', 'A mutual NDA template in plain language.', 40],
      ['Company policy handbook', 'Leave, conduct and remote work policies in one handbook.', 200],
      ['Business plan document', 'A structured business plan from your notes and numbers.', 250],
      ['Grant or tender application', 'A complete application drafted from your materials.', 220],
      ['Supplier agreement draft', 'A supply agreement drafted around your terms, for legal review.', 150],
      ['Investor update template', 'A monthly investor update template with metrics and narrative sections.', 70],
      ['Contract summary', 'A plain-language summary of a contract up to 20 pages.', 60],
      ['Employment offer letters', 'Offer letter and contract templates for new hires.', 90],
    ],
    requests: [
      ['Need a reusable freelance services contract, to be checked by our lawyer.', 90],
      ['Looking for someone to draft our website terms and privacy policy.', 110],
      ['Need a business plan written for a bank loan application.', 220],
      ['Want a plain-language summary of a 15-page supplier contract.', 60],
      ['Need a grant application drafted for a small agritech project.', 200],
    ],
  },
  {
    id: 'hr-recruiting', lane: 'service',
    offers: [
      ['CV and cover letter rewrite', 'A rewritten CV and a tailored cover letter for one role.', 45],
      ['LinkedIn profile makeover', 'Headline, about section and experience rewritten for search.', 50],
      ['Job description writing', 'Three clear job descriptions with requirements and pay bands.', 60],
      ['Candidate sourcing', 'Fifteen screened candidates for one role, with notes.', 200],
      ['Interview scheduling and screening', 'Screening calls with up to ten candidates and a shortlist.', 180],
      ['Onboarding checklist', 'A first-month onboarding plan for new hires.', 55],
      ['Salary benchmark', 'Pay ranges for one role from public data, with sources.', 90],
      ['Remote hiring process setup', 'A hiring pipeline set up in a free applicant tracker.', 140],
      ['Staff handbook review', 'A review of your handbook with gaps listed.', 80],
      ['Interview question bank', 'Forty structured interview questions with scoring notes.', 45],
    ],
    requests: [
      ['Need 10 screened candidates for a junior developer role.', 180],
      ['Looking for someone to rewrite three job descriptions.', 60],
      ['Need salary benchmarks for a customer support role.', 80],
      ['Want an onboarding plan for our first five hires.', 70],
      ['Need a hiring pipeline set up for a growing sales team.', 130],
    ],
  },
  {
    id: 'photo-video', lane: 'service',
    offers: [
      ['Product photography', 'Ten edited product photos on a clean background, shot at our studio.', 150, true],
      ['Event photography', 'Four hours of event coverage with 100 edited photos.', 220, true],
      ['Headshot session', 'A one-hour session with five retouched headshots.', 80, true],
      ['Promo video edit', 'A 60-second promo edited from your footage with music and titles.', 180],
      ['YouTube video editing', 'One video up to 15 minutes edited with cuts, captions and a thumbnail.', 120],
      ['Photo retouching', 'Retouching of up to 20 photos.', 40],
      ['Real estate photography', 'Interior and exterior photos of one property, 25 edited images.', 170, true],
      ['Wedding highlight film', 'A three-to-five-minute highlight film from your wedding footage.', 400],
      ['Drone footage edit', 'A short edit from your drone clips with colour grading.', 140],
      ['Food photography', 'Twelve styled and edited dish photos for menus and delivery apps.', 130, true],
    ],
    requests: [
      ['Need product photos for 15 items on a white background.', 140, true],
      ['Looking for a photographer for a four-hour launch event.', 200, true],
      ['Need a 60-second promo video cut from existing footage.', 150],
      ['Want team headshots for six people.', 120, true],
      ['Need a YouTube video edited with captions and a thumbnail.', 90],
    ],
  },
  {
    id: 'translation', lane: 'service',
    offers: [
      ['English to French translation', 'Translation of up to 2,000 words, proofread by a second linguist.', 90],
      ['English to Arabic translation', 'Translation of up to 2,000 words with right-to-left layout checked.', 110],
      ['Official document translation', 'Translation of official documents formatted for certification.', 150],
      ['Website localisation', 'Your site translated into one language, with search terms adapted.', 250],
      ['Subtitle translation', 'Translated subtitles for a video up to 20 minutes.', 80],
      ['English to Swahili translation', 'Translation of up to 2,000 words for East African readers.', 90],
      ['English to Portuguese translation', 'Translation of up to 2,000 words for Brazilian readers.', 95],
      ['Audio transcription', 'Transcription of up to 60 minutes of audio with timestamps.', 50],
      ['Translation proofreading', 'A native-speaker check of an existing translation up to 3,000 words.', 45],
      ['App localisation', 'App strings translated into one language with context checks.', 170],
    ],
    requests: [
      ['Need our website translated into French for new customers.', 200],
      ['Looking for Swahili subtitles for a 10-minute product video.', 70],
      ['Need a contract translated from English to Arabic.', 120],
      ['Want 45 minutes of interview audio transcribed with timestamps.', 45],
      ['Need our app strings localised into Portuguese.', 130],
    ],
  },
  {
    id: 'voice-audio', lane: 'service',
    offers: [
      ['Commercial voice-over', 'A 30-second ad read, recorded and cleaned, with two takes.', 120],
      ['Explainer video narration', 'Narration up to 2 minutes, synced to your video.', 150],
      ['Phone system greetings', 'Up to five recorded phone system prompts.', 60],
      ['Audiobook narration', 'Narration of up to 20,000 words with edits and mastering.', 400],
      ['E-learning narration', 'Narration for up to 10 short course modules.', 200],
      ['Podcast editing', 'One episode up to 60 minutes edited, with noise removal.', 90],
      ['Radio jingle', 'A 15-second jingle with voice and a music bed.', 180],
      ['Character voices for animation', 'Up to three character voices for a short animation.', 160],
      ['Pidgin English voice-over', 'A natural Pidgin read up to 60 seconds for ads or explainers.', 90],
      ['Audio clean-up', 'Noise and echo removed from up to 30 minutes of audio.', 50],
    ],
    requests: [
      ['Need a 30-second radio ad voiced in Pidgin English.', 100],
      ['Looking for narration for a two-minute explainer video.', 130],
      ['Need our podcast episodes edited, two episodes of about 45 minutes.', 150],
      ['Want phone greetings recorded for our customer line.', 50],
      ['Need a short jingle for a campus radio campaign.', 150],
    ],
  },
  {
    id: 'music-production', lane: 'service',
    offers: [
      ['Afrobeats instrumental', 'An original instrumental with stems, licensed for one release.', 150],
      ['Mixing and mastering', 'Mix and master of one song from your stems.', 120],
      ['Podcast intro music', 'A 20-second intro and outro theme.', 70],
      ['Brand sonic logo', 'A three-second audio signature in several versions.', 110],
      ['Background music for video', 'A two-minute royalty-free track for your video.', 90],
      ['Songwriting session', 'Lyrics and melody for one song, written with you.', 130],
      ['Vocal tuning and editing', 'Timing and pitch editing of one lead vocal.', 60],
      ['Beat for a short ad', 'A 30-second beat built around your ad script.', 80],
      ['Stem separation', 'Vocals and instruments separated from a finished track.', 40],
      ['Music for a mobile game', 'Three looping tracks and five sound effects.', 200],
    ],
    requests: [
      ['Need an original Afrobeats instrumental for a single.', 150],
      ['Looking for mixing and mastering on a four-song EP.', 300],
      ['Need a short intro theme for a weekly podcast.', 60],
      ['Want a sonic logo for our fintech app.', 110],
      ['Need looping background music for a casual mobile game.', 180],
    ],
  },
  {
    id: 'tutoring', lane: 'service',
    offers: [
      ['Maths tutoring, secondary school', 'Eight one-hour online lessons with practice sets.', 120],
      ['Coding lessons for beginners', 'Eight online lessons on Python or JavaScript with a small project.', 160],
      ['IELTS preparation', 'Six online lessons with two marked practice tests.', 130],
      ['Excel for business course', 'Four live online sessions from basics to pivot tables.', 90],
      ['French conversation lessons', 'Eight 45-minute online conversation lessons.', 110],
      ['Online course creation', 'A short course outline, slides and scripts for five lessons.', 250],
      ['Exam revision plan', 'A personal revision plan with weekly check-ins for a month.', 70],
      ['Public speaking coaching', 'Four online sessions with recorded practice and feedback.', 140],
      ['Digital skills for small business', 'Three online sessions on email, spreadsheets and online payments.', 80],
      ['University application support', 'Personal statement editing and a document checklist.', 100],
    ],
    requests: [
      ['Need a maths tutor for a 15-year-old, twice a week for a month.', 120],
      ['Looking for IELTS lessons with marked practice tests.', 110],
      ['Need a beginner Python course for three staff members.', 200],
      ['Want someone to turn our training notes into a short online course.', 220],
      ['Need help editing a personal statement for a master\'s application.', 80],
    ],
  },
  {
    id: 'phones-electronics', lane: 'goods',
    offers: [
      ['Used iPhone 13, 128 GB', 'Unlocked, battery health above 85 percent, tested and wiped, with a charger.', 420],
      ['Samsung Galaxy A54 5G', 'New in box, 128 GB.', 290],
      ['Refurbished MacBook Air M1', '8 GB RAM, 256 GB SSD, clean battery report, with a charger.', 650],
      ['Tecno Camon 20', 'New in box, 256 GB, dual SIM.', 170],
      ['AirPods Pro, second generation', 'Sealed in box, with the MagSafe case.', 180],
      ['Power bank, 20,000 mAh', 'Fast charging with two USB ports and USB-C.', 25],
      ['Solar home kit', 'Panel, battery and three bulbs, enough for lights and phone charging.', 240],
      ['Wi-Fi 6 router', 'Dual-band router, new in box.', 55],
      ['Used iPad, 9th generation', '64 GB Wi-Fi model, screen and battery in good condition.', 230],
      ['Fitness smartwatch', 'Heart rate and sleep tracking with a two-week battery.', 70],
    ],
    requests: [
      ['Looking to buy a used iPhone 12 or 13 in good condition, unlocked.', 350],
      ['Need five power banks for our field team.', 120],
      ['Want a refurbished laptop for design work, at least 16 GB RAM.', 450],
      ['Need a solar kit to keep a small shop lit during outages.', 220],
      ['Looking for two Wi-Fi routers for a small office.', 100],
    ],
  },
  {
    id: 'fashion-tailoring', lane: 'goods',
    offers: [
      ['Ankara two-piece set', 'Made to your measurements from quality Ankara fabric.', 60],
      ["Men's senator outfit", 'Tailored top and trousers, made to measure.', 75],
      ['Agbada three-piece', 'Embroidered agbada made to measure for events.', 180],
      ['Wedding guest dress', 'Designed with you and made to measure.', 140],
      ['Adire fabric, 6 yards', 'Hand-dyed adire from Abeokuta.', 35],
      ['Handmade leather sandals', 'Made in Aba, sizes 38 to 46.', 40],
      ['Aso-oke set', 'Gele, ipele and iro woven to order for ceremonies.', 150],
      ["Children's native outfit", 'Made to measure for ages 2 to 12.', 30],
      ['Kente stole', 'Handwoven kente stole for graduations.', 45],
      ['Ankara tote bag', 'A lined tote bag in Ankara print with an inner pocket.', 25],
    ],
    requests: [
      ['Need matching Ankara outfits for a team of six for a trade fair.', 300],
      ['Looking for a tailor to make a senator outfit for a wedding next month.', 80],
      ['Want 12 yards of hand-dyed adire for a design project.', 70],
      ['Need aso-oke sets for a family ceremony, four people.', 400],
      ['Looking for handmade leather sandals in bulk, 20 pairs.', 450],
    ],
  },
  {
    id: 'home-crafts', lane: 'goods',
    offers: [
      ['Handwoven raffia basket set', 'Three nesting baskets for storage.', 40],
      ['Carved wooden serving tray', 'Carved from mahogany with a food-safe finish.', 35],
      ['Beaded necklace', 'A handmade glass bead necklace.', 25],
      ['Scented soy candles, set of 4', 'Soy wax candles in local scents.', 30],
      ['Mudcloth pillow covers, set of 2', 'Covers in a mudcloth pattern, 45 by 45 cm.', 28],
      ['Clay cooking pot', 'A traditional clay pot for soups and stews.', 32],
      ['Woven wall hanging', 'Handwoven wall art, about 60 by 90 cm.', 50],
      ['Brass figurine', 'A hand-cast brass figurine in the Benin tradition.', 90],
      ['Leather notebook', 'A hand-stitched leather notebook with refillable pages.', 30],
      ['Woven table mats, set of 6', 'Handwoven mats in natural fibre.', 24],
    ],
    requests: [
      ['Need 30 raffia baskets for a hotel room refresh.', 400],
      ['Looking for brass figurines as corporate gifts, ten pieces.', 450],
      ['Want handmade gift sets for 25 clients, candles or notebooks.', 350],
      ['Need carved wooden trays for a restaurant, 12 pieces.', 300],
      ['Looking for woven wall art for a new office, three pieces.', 140],
    ],
  },
  {
    id: 'beauty-products', lane: 'goods',
    offers: [
      ['Shea butter, 1 kg', 'Unrefined grade A shea butter.', 18],
      ['African black soap, 12 bars', 'Traditional black soap from Ghana.', 22],
      ['Natural hair care set', 'Oil, butter and leave-in conditioner in one set.', 26],
      ['Cold-pressed coconut oil, 1 litre', 'Virgin coconut oil for skin and hair.', 15],
      ['Hibiscus face mask, 6 jars', 'A clay and hibiscus mask in 100 g jars.', 30],
      ['Body butter gift box', 'Three whipped body butters in a gift box.', 28],
      ['Chebe hair powder, 250 g', 'Traditional chebe powder for hair care.', 20],
      ['Beard care kit', 'Beard oil, balm and a wooden comb.', 24],
      ['Handmade lip balm, 12 pack', 'Shea and beeswax lip balms.', 18],
      ['Private-label skincare samples', 'Twenty sample pots of our base creams for your brand trial.', 60],
    ],
    requests: [
      ['Need 10 kg of unrefined shea butter for a skincare line.', 150],
      ['Looking for black soap in bulk, 100 bars.', 160],
      ['Want 40 body butter gift boxes for a corporate order.', 450],
      ['Need private-label cream samples to test a new brand.', 80],
      ['Looking for natural hair care sets to stock in a salon, 20 sets.', 400],
    ],
  },
  {
    id: 'packaging-printing', lane: 'goods',
    offers: [
      ['Branded paper bags, 200 pieces', 'Kraft paper bags printed with your logo in one colour.', 120],
      ['Custom mailer boxes, 100 pieces', 'Corrugated mailer boxes printed on the outside.', 180],
      ['Product labels, 1,000 pieces', 'Waterproof printed labels in your size.', 60],
      ['Business cards, 500 pieces', 'Matte cards printed on 350 gsm stock.', 30],
      ['Branded stickers, 500 pieces', 'Die-cut vinyl stickers of your logo.', 40],
      ['Roll-up banner', 'An 85 by 200 cm banner with a carry case.', 70],
      ['Printed tote bags, 50 pieces', 'Cotton tote bags printed with your artwork.', 150],
      ['Food packaging containers, 300 pieces', 'Paper takeaway containers with your logo.', 140],
      ['Thank-you cards, 250 pieces', 'Printed insert cards for your parcels.', 35],
      ['Branded tape, 12 rolls', 'Packing tape printed with your logo.', 45],
    ],
    requests: [
      ['Need 300 printed mailer boxes for an online store.', 400],
      ['Looking for 2,000 waterproof labels for juice bottles.', 150],
      ['Want 100 printed tote bags for a conference.', 280],
      ['Need a roll-up banner and 500 flyers for an exhibition.', 120],
      ['Looking for branded takeaway packaging for a restaurant, 500 pieces.', 220],
    ],
  },
];

/// Five specialties per account, in the operator's order, and a line about that
/// account's business that names the market each request comes from.
export const ACCOUNT_GROUPS: ReadonlyArray<{ specialties: readonly string[]; context: string }> = [
  { specialties: ['brand-design', 'social-content', 'copywriting', 'game-3d-art', 'event-planning'], context: 'It is for a creative studio with clients in {market}.' },
  { specialties: ['web-development', 'qa-testing', 'technical-writing', 'software-ai', 'smart-contracts'], context: 'It is for a software team serving users in {market}.' },
  { specialties: ['bookkeeping', 'data-analysis', 'virtual-assistance', 'legal-docs', 'hr-recruiting'], context: 'It is for a business services firm with clients in {market}.' },
  { specialties: ['photo-video', 'translation', 'voice-audio', 'music-production', 'tutoring'], context: 'It is for a media and learning studio with audiences in {market}.' },
  { specialties: ['phones-electronics', 'fashion-tailoring', 'home-crafts', 'beauty-products', 'packaging-printing'], context: 'It is for an online shop selling to customers in {market}.' },
];
